name: File-Manager produce binaries

on:
  workflow_dispatch:
    inputs:
      build_from:
        description: 'The branch name or commit hash or tag to base the build on'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: "kitswas/File-Manager"

          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: ${{ inputs.build_from }} 

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.1
          target: desktop
          cache: true

      - name: Cmake build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Show debug info
        if: matrix.os != 'windows-latest'
        run: |
          pwd
          ls -la build
          ls -la
          ls -la ..

      - name: Windows deployment
        if: matrix.os == 'windows-latest'
        run: |
          cd ./build/Release
          windeployqt File-Manager.exe

      - name: MacOS deployment
        if: matrix.os == 'macOS-latest'
        run: |
          cd build
          macdeployqt File-Manager.app -verbose=2
          sudo chmod +x File-Manager.app
          sudo chmod +x File-Manager.app/Contents/MacOS/*
          mkdir MacOS
          mv File-Manager.app MacOS

      - name: Save build artifacts Windows
        if:  matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "File-Manager-Windows"
          path: ./build/Release

      - name: Save build artifacts MacOS
        if:  matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "File-Manager-MacOS.app"
          path: ./build/MacOS
